; ====================================================
; ================== Global Custom =================== 
; ====================================================

[custom] ; options valid for all builds
build_flags =
  -D SERIAL_DEBUG=Serial
  -D OPENKNX_MAX_LOG_MESSAGE_LENGTH=1024
  -D OPENKNX_LEDFUNC_BASE_PROG_UNCONFIGUREDSUPPORT

[custom_develop] ; options valid only for develop builds
extends = custom
build_flags =
  ${custom.build_flags}
  ;-D OPENKNX_HEARTBEAT
  -D OPENKNX_HEARTBEAT_PRIO
  ;-D OPENKNX_RTT
  ;-D BUFFER_SIZE_UP=10240
  ;-D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
  ;-D LOGIC_TRACE
  ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
  ;"-D OPENKNX_TRACE1=OTAUpdateModule.*"
  ;"-D OPENKNX_TRACE2=Flash.*"
debug_build_flags = -ggdb3
  -O0

[custom_release] ; options valid only for release builds
extends = custom
build_flags =
  ${custom.build_flags}


; ====================================================
; ====================== RP2040 ====================== 
; ====================================================
[RP2040_custom] ; options valid for all RP2040 builds
build_flags = 
  -D USE_KNX_DMA_UART=0
  -D USE_KNX_DMA_IRQ=0
  -Wunused-variable
  -lalgobsec
  ${KNX_TP.build_flags} ; all RP2040 builds use TP


[RP2040_custom_develop] ; normally, do not add something here.
extends = RP2040_develop, custom_develop, RP2040_custom
build_flags = 
  ${RP2040_develop.build_flags}
  ${custom_develop.build_flags}
  ${RP2040_custom.build_flags}


[RP2040_custom_releases] ; normally, do not add something here.
extends = RP2040_releases, custom_release, RP2040_custom
build_flags = 
  ${RP2040_releases.build_flags}
  ${custom.build_flags}
  ${RP2040_custom.build_flags}


; ====================================================
; ====================== ESP32 ======================= 
; ====================================================
[ESP32_custom] ; options valid for all ESP32 builds
build_flags =
  -D OPENKNX_USB_EXCHANGE_IGNORE

[custom_develop_ESP32] ; normally, do not add something here.
extends = ESP32_develop, custom_develop, ESP32_custom
build_type = release ; Use release because debug causes app crash at startup for unknown reason
build_flags =
  -g ; Generate debug info - used instead of build_type=debug 
  ${ESP32_develop.build_flags}
  ${custom_develop.build_flags} 
  ${ESP32_custom.build_flags} 

[custom_release_ESP32] ; normally, do not add something here.
extends = ESP32_releases, custom_release, ESP32_custom
build_flags =
  ${ESP32_releases.build_flags}
  ${custom_release.build_flags}
  ${ESP32_custom.build_flags} 


; ================== UP1-GW-UART =================== 
[board_OpenKNX_UP1_GW_UART]
extends = 
build_flags =
  -D DEVICE_UP1_GW_UART
  -D SENSORMODULE
  -D OPENKNX_AIR_CONDITION_SERIAL=Serial2
  -D OPENKNX_AIR_CONDITION_SERIAL_TX=UART1_TX_PIN
  -D OPENKNX_AIR_CONDITION_SERIAL_RX=UART1_RX_PIN

[env:develop_OpenKNX_UP1_GW_UART]
extends = RP2040_custom_develop, board_OpenKNX_UP1_GW_UART
build_flags =
  ${RP2040_custom_develop.build_flags}
  ${board_OpenKNX_UP1_GW_UART.build_flags}

[env:release_OpenKNX_UP1_GW_UART]
extends = RP2040_custom_releases, board_OpenKNX_UP1_GW_UART
build_flags =
  ${RP2040_custom_releases.build_flags}
  ${board_OpenKNX_UP1_GW_UART.build_flags}

; ================== OPENKNXIAO-esp32s3-mini-V1 =================== 
[oknxhw_OPENKNXIAO_ESP32S3_MINI_V1]
extends = ESP32_8MB
board = seeed_xiao_esp32s3
build_flags =
  -D OKNXHW_OPENKNXIAO_ESP32S3_MINI_V1
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  -D KNX_IP_WIFI
  ${KNX_IP.build_flags}
  -D OPENKNX_AIR_CONDITION_SERIAL=Serial2
  -D OPENKNX_AIR_CONDITION_SERIAL_TX=OKNXHW_OPENKNXIAO_D4
  -D OPENKNX_AIR_CONDITION_SERIAL_RX=OKNXHW_OPENKNXIAO_D2

[env:develop_OPENKNXIAO_ESP32S3_MINI_V1]
extends = custom_develop_ESP32, oknxhw_OPENKNXIAO_ESP32S3_MINI_V1
build_flags =
  ${oknxhw_OPENKNXIAO_ESP32S3_MINI_V1.build_flags}
  ${custom_develop_ESP32.build_flags}

[env:release_OPENKNXIAO_ESP32S3_MINI_V1]
extends = custom_release_ESP32, oknxhw_OPENKNXIAO_ESP32S3_MINI_V1
build_flags =
  ${oknxhw_OPENKNXIAO_ESP32S3_MINI_V1.build_flags}
  ${custom_release_ESP32.build_flags}

; ================== UP1-WLAN-2xUART =================== 
[board_OpenKNX_UP1_WLAN_2XUART]
extends = ESP32_8MB
board = seeed_xiao_esp32s3
build_flags =
  -D DEVICE_UP1_WLAN_2XUART
  -D DEVICE_UP1_WLAN_2XUART_ONBOARD ; just for test, remove later
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
  -D KNX_IP_WIFI
  ${KNX_IP.build_flags}
  -D OPENKNX_AIR_CONDITION_SERIAL=Serial2
  -D OPENKNX_AIR_CONDITION_SERIAL_TX=UART1_TX_PIN
  -D OPENKNX_AIR_CONDITION_SERIAL_RX=UART1_RX_PIN

[env:develop_OpenKNX_UP1_WLAN_2XUART]
extends = custom_develop_ESP32, board_OpenKNX_UP1_WLAN_2XUART
build_flags =
  ${board_OpenKNX_UP1_WLAN_2XUART.build_flags}
  ${custom_develop_ESP32.build_flags}


[env:release_OpenKNX_UP1_WLAN_2XUART]
extends = custom_release_ESP32, board_OpenKNX_UP1_WLAN_2XUART
build_flags =
  ${board_OpenKNX_UP1_WLAN_2XUART.build_flags}
  ${custom_release_ESP32.build_flags}




; ============= Waveshare ESP32-S3-Zero ============== 
[board_Waveshare_ESP32_S3_Zero]
extends = ESP32_4MB
board = esp32-s3-devkitm-1
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM
  -D PROG_BUTTON_PIN=0
 # -D OPENKNX_SERIALLED_ENABLE
 # -D OPENKNX_SERIALLED_PIN=21
 # -D OPENKNX_SERIALLED_COLOR_RED=50,0,0
 # -D OPENKNX_SERIALLED_COLOR_GREEN=0,35,0
 # -D OPENKNX_SERIALLED_COLOR_BLUE=0,0,63
 # -D OPENKNX_SERIALLED_COLOR_YELLOW=40,30,0
 # -D OPENKNX_SERIALLED_NUM=1
  -D PROG_LED_PIN=11
  -D PROG_LED_PIN_ACTIVE_ON=1
  -D PROG_LED_COLOR=OPENKNX_SERIALLED_COLOR_RED
  -D KNX_UART_NUM=1
  -D KNX_UART_RX_PIN=16
  -D KNX_UART_TX_PIN=17
  -D KNX_IP_WIFI
  -D OPENKNX_AIR_CONDITION_SERIAL=Serial2
  -D OPENKNX_AIR_CONDITION_SERIAL_TX=27
  -D OPENKNX_AIR_CONDITION_SERIAL_RX=26

[env:develop_Waveshare_ESP32_S3_Zero_TP]
extends = ESP32_develop, custom_develop_ESP32, custom_develop, board_Waveshare_ESP32_S3_Zero
monitor_speed = 921600
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_Waveshare_ESP32_S3_Zero.build_flags}
  -D DEVELOPMENT

[env:develop_Waveshare_ESP32_S3_Zero_TP_USB]
extends = ESP32_UPLOAD_USB, env:develop_Waveshare_ESP32_S3_Zero_TP


; ============= AZDelivery ESP32 Board Dev Kit C V4 ============== 
[board_AZDelivery_DevKit_C_V4]
board = esp32dev
extends = ESP32_4MB
build_flags =
  -D DEVICE_ID='"AZD-ESP32-DevKit-V4"'
  -D DEVICE_NAME='"AZDelivery ESP32 Board Dev Kit C V4"'
  -D PROG_BUTTON_PIN=0
  -D PROG_LED_PIN=2
  -D PROG_LED_PIN_ACTIVE_ON=1
  -D KNX_UART_NUM=1
  -D KNX_UART_RX_PIN=16
  -D KNX_UART_TX_PIN=17
  -D KNX_IP_WIFI
  -D OPENKNX_AIR_CONDITION_SERIAL=Serial2
  -D OPENKNX_AIR_CONDITION_SERIAL_TX=27
  -D OPENKNX_AIR_CONDITION_SERIAL_RX=26

[env:develop_AZDelivery_DevKit_C_V4_TP]
extends = ESP32_develop, custom_develop_ESP32, custom_develop, board_AZDelivery_DevKit_C_V4
build_flags =
  ${KNX_TP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_AZDelivery_DevKit_C_V4.build_flags}
  -D DEVELOPMENT
 
[env:develop_AZDelivery_DevKit_C_V4_TP_USB]
extends = ESP32_UPLOAD_USB, env:develop_AZDelivery_DevKit_C_V4_TP

[env:develop_AZDelivery_DevKit_C_V4_IP]
extends = ESP32_develop, custom_develop_ESP32, custom_develop, board_AZDelivery_DevKit_C_V4
build_flags =
  ${KNX_IP.build_flags}
  ${ESP32_develop.build_flags}
  ${custom_develop_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_AZDelivery_DevKit_C_V4.build_flags}
  -D DEVELOPMENT
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0

[env:develop_AZDelivery_DevKit_C_V4_IP_USB]
extends = ESP32_UPLOAD_USB, env:develop_AZDelivery_DevKit_C_V4_IP

[env:release_AZDelivery_DevKit_C_V4_TP]
extends = custom_release_ESP32, board_AZDelivery_DevKit_C_V4
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_AZDelivery_DevKit_C_V4.build_flags}
   ${KNX_TP.build_flags}

[env:release_AZDelivery_DevKit_C_V4_TP_OTA]
extends = custom_release_ESP32, board_AZDelivery_DevKit_C_V4
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_AZDelivery_DevKit_C_V4.build_flags}
   ${KNX_TP.build_flags}
  upload_protocol = espota
  upload_port = #192.168.0.14 # IP Address

[env:release_AZDelivery_DevKit_C_V4_IP]
extends = custom_release_ESP32, board_AZDelivery_DevKit_C_V4
build_flags =
   ${custom_release_ESP32.build_flags}  
   ${board_AZDelivery_DevKit_C_V4.build_flags}
  ${KNX_IP.build_flags}
  -D OPENKNX_OVERRIDE_MASK_VERSION=0x07B0
